### ISSUE TITLE
ERROR 9002 (28000): SSL connection is required. Please specify SSL options and retry.

### ISSUE THREAD

**Issue by JovinLeong** [paladique/Workshop-DataInAzure#3]
Hi, not sure if you'll see this, but I've been following both the video instructions and the README instructions to the letter but I get the following error when trying use the MySQL Cloud Shell.

ERROR 9002 (28000): SSL connection is required. Please specify SSL options and retry.

My client IP address has already been added, I've tried disabling SSL settings, and I've tried redeploying several times but to no avail. Any insights? Is there something missing in your instructions perhaps or something I might have missed by following the video?

**Comment by paladique** [comment]
Hi @JovinLeong, sorry for the delay here - looks like the process for logging in via cloud shell changed. Thankfully it hasn't changed too much: you'll just need to bind the SSL certificate. Here's the docs for reference: https://docs.microsoft.com/en-us/azure/mysql/howto-configure-ssl#step-1-obtain-ssl-certificate.

Here's how to connect, according to the docs:

- Download the SSL Certificate (download the new one)
- Upload the downloaded certificate to your cloud shell (confirm it's uploaded with `ls`)
- Login again to mysql with `mysql -h servername.mysql.database.azure.com -u adminname@servername -p--ssl-ca=DigiCertGlobalRootG2.crt.pem`

Hope this helps!
